name: Test-my-action
on: 
  push:
    branches:
      - main

jobs:   
  test:
    name: 'Test my action'  
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: matichewer/eati2023-test-my-action@main
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
