name: Pipeline
on: 
  push:
    branches:
      - main

jobs:   
  test:
    name: 'Test action'  
    runs-on: ubuntu-latest
    steps: 
      - name: 'Checkout repo de matichewer/eati2023-test-my-action@main'
        uses: matichewer/eati2023-test-my-action@main
        with:
          repository: matichewer/eati2023-test-my-action

