name: Pipeline
on: 
  push:
    branches:
      - main

jobs:   
  test:
    name: 'Test action'  
    runs-on: ubuntu-latest
    steps: 
      - name: 'Test action de matichewer/eati2023-test-my-action@v1'
        uses: matichewer/eati2023-test-my-action@v1

